// report-pdf/index.ts
// Generates PDF documents (invoices, receipts, settlements, reports)
// and uploads them to the documents-pdf storage bucket.
//
// Invoke: POST with JSON body { type, id }
//   type: "invoice" | "receipt" | "settlement" | "report"
//   id:   the document/booking/settlement ID
//
// Deploy: supabase functions deploy report-pdf --no-verify-jwt

import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const supabase = createClient(
  Deno.env.get("SUPABASE_URL") ?? "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
);

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("en-US", { minimumFractionDigits: 2 }).format(amount);
}

function invoiceHtml(doc: any, customer: any, booking: any, settings: any): string {
  const rows = booking ? `
    <tr><td>Rental days</td><td>${booking.rental_days}</td></tr>
    <tr><td>Daily rate</td><td>${formatCurrency(booking.daily_rate)}</td></tr>
    <tr><td>Subtotal</td><td>${formatCurrency(doc.subtotal)}</td></tr>
    <tr><td>Tax</td><td>${formatCurrency(doc.tax_amount)}</td></tr>
    <tr><td><strong>Total</strong></td><td><strong>${formatCurrency(doc.total)}</strong></td></tr>
    <tr><td>Paid</td><td>${formatCurrency(doc.paid_amount)}</td></tr>
    <tr><td><strong>Balance</strong></td><td><strong>${formatCurrency(doc.balance)}</strong></td></tr>
  ` : `
    <tr><td>Subtotal</td><td>${formatCurrency(doc.subtotal)}</td></tr>
    <tr><td>Tax</td><td>${formatCurrency(doc.tax_amount)}</td></tr>
    <tr><td><strong>Total</strong></td><td><strong>${formatCurrency(doc.total)}</strong></td></tr>
    <tr><td>Paid</td><td>${formatCurrency(doc.paid_amount)}</td></tr>
    <tr><td><strong>Balance</strong></td><td><strong>${formatCurrency(doc.balance)}</strong></td></tr>
  `;
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #1e293b; }
    .header { display: flex; justify-content: space-between; margin-bottom: 30px; }
    .business { font-size: 20px; font-weight: bold; }
    .business-info { font-size: 12px; color: #64748b; margin-top: 4px; }
    .invoice-title { font-size: 24px; font-weight: bold; text-align: right; }
    .invoice-number { font-size: 14px; color: #64748b; text-align: right; }
    .customer { margin-bottom: 20px; }
    .customer h3 { font-size: 14px; color: #64748b; margin-bottom: 4px; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    td { padding: 8px 12px; border-bottom: 1px solid #e2e8f0; }
    td:first-child { color: #64748b; }
    .total-row { font-weight: bold; background: #f8fafc; }
    .footer { margin-top: 40px; font-size: 11px; color: #94a3b8; text-align: center; }
  </style></head><body>
    <div class="header">
      <div>
        <div class="business">${escapeHtml(settings.business_name)}</div>
        <div class="business-info">${escapeHtml(settings.address ?? "")}</div>
        ${settings.tax_reg_number ? `<div class="business-info">Tax Reg: ${escapeHtml(settings.tax_reg_number)}</div>` : ""}
      </div>
      <div>
        <div class="invoice-title">${escapeHtml(doc.type)}</div>
        <div class="invoice-number">${escapeHtml(doc.number)}</div>
        <div class="invoice-number">${new Date(doc.date).toLocaleDateString()}</div>
      </div>
    </div>
    <div class="customer">
      <h3>Bill To</h3>
      <div>${escapeHtml(customer?.full_name ?? customer?.company_name ?? "—")}</div>
      ${customer?.phone ? `<div>${escapeHtml(customer.phone)}</div>` : ""}
      ${customer?.email ? `<div>${escapeHtml(customer.email)}</div>` : ""}
    </div>
    <table>${rows}</table>
    <div class="footer">Generated by RentFlow</div>
  </body></html>`;
}

Deno.serve(async (req: Request) => {
  try {
    if (req.method !== "POST") {
      return new Response("Method not allowed. Use POST with { type, id }", { status: 405 });
    }

    const { type, id } = await req.json();
    if (!type || !id) {
      return new Response(JSON.stringify({ error: "Missing type or id" }), {
        status: 400, headers: { "Content-Type": "application/json" },
      });
    }

    // Fetch settings
    const { data: settings } = await supabase.from("settings").select("*").eq("id", 1).single();
    if (!settings) throw new Error("Settings not found");

    let html = "";
    let fileName = "";

    if (type === "invoice" || type === "receipt") {
      const { data: doc } = await supabase.from("documents").select("*").eq("id", id).single();
      if (!doc) throw new Error("Document not found");

      const { data: customer } = doc.customer_id
        ? await supabase.from("customers").select("*").eq("id", doc.customer_id).single()
        : { data: null };

      const { data: booking } = doc.booking_id
        ? await supabase.from("bookings").select("*").eq("id", doc.booking_id).single()
        : { data: null };

      html = invoiceHtml(doc, customer, booking, settings);
      fileName = `${doc.number}.html`;
    } else if (type === "settlement") {
      const { data: settlement } = await supabase.from("settlements").select("*").eq("id", id).single();
      if (!settlement) throw new Error("Settlement not found");
      const { data: investor } = await supabase.from("investors").select("*").eq("id", settlement.investor_id).single();
      html = `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        table { width: 100%; border-collapse: collapse; }
        td { padding: 8px; border-bottom: 1px solid #e2e8f0; }
      </style></head><body>
        <h2>Settlement ${escapeHtml(settlement.number)}</h2>
        <p>Investor: ${escapeHtml(investor?.full_name ?? "—")}</p>
        <p>Period: ${escapeHtml(settlement.period)}</p>
        <p>Amount: ${formatCurrency(settlement.amount)}</p>
        <p>Status: ${escapeHtml(settlement.status)}</p>
      </body></html>`;
      fileName = `${settlement.number}.html`;
    } else {
      return new Response(JSON.stringify({ error: `Unknown type: ${type}` }), {
        status: 400, headers: { "Content-Type": "application/json" },
      });
    }

    // Upload to storage
    const filePath = `${type}/${fileName}`;
    const { error: uploadError } = await supabase.storage
      .from("documents-pdf")
      .upload(filePath, new TextEncoder().encode(html), {
        contentType: "text/html",
        upsert: true,
      });

    if (uploadError) throw uploadError;

    // Generate signed URL (valid for 1 hour)
    const { data: urlData } = await supabase.storage
      .from("documents-pdf")
      .createSignedUrl(filePath, 3600);

    return new Response(JSON.stringify({
      ok: true,
      path: filePath,
      url: urlData?.signedUrl,
    }), { headers: { "Content-Type": "application/json" } });
  } catch (err) {
    return new Response(JSON.stringify({ error: String(err) }), { status: 500 });
  }
});
